<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DM.Domain.Core\DM.Domain.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>
</Project>
