<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <PackageReference Include="Jamq.Client.Rabbit.DependencyInjection" />
        <PackageReference Include="Polly" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DM.Domain.Account\DM.Domain.Account.csproj" />
        <ProjectReference Include="..\DM.Domain.Community\DM.Domain.Community.csproj" />
        <ProjectReference Include="..\DM.Domain.Personal\DM.Domain.Personal.csproj" />
        <ProjectReference Include="..\DM.Infrastructure.Core\DM.Infrastructure.Core.csproj" />
        <ProjectReference Include="..\DM.Infrastructure.Persistence\DM.Infrastructure.Persistence.csproj" />
        <ProjectReference Include="..\DM.Infrastructure.Mail\DM.Infrastructure.Mail.csproj" />
        <ProjectReference Include="..\DM.Infrastructure.Messaging\DM.Infrastructure.Messaging.csproj" />
    </ItemGroup>

</Project>
