using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DM.Domain.Core.Dto;
using DM.Domain.Personal.Features.Notifications;
using DM.Infrastructure.Persistence.Entities.Personal.Notifications;
using DM.Infrastructure.Persistence.MongoIntegration;
using MongoDB.Driver;

namespace DM.Infrastructure.Persistence.Repositories.Personal;

/// <inheritdoc cref="INotificationRepository" />
internal class NotificationRepository : MongoCollectionRepository<Notification>, INotificationRepository
{
    /// <inheritdoc />
    public NotificationRepository(DmMongoClient client) : base(client)
    {
    }

    // ═══ READ ═══

    /// <inheritdoc />
    public Task<long> Count(Guid userId) => Collection.CountDocumentsAsync(UserInterested(userId));

    /// <inheritdoc />
    public Task<long> CountUnread(Guid userId) => Collection.CountDocumentsAsync(UserToBeNotified(userId));

    /// <inheritdoc />
    public async Task<IEnumerable<UserNotification>> GetNotifications(Guid userId, PagingData pagingData)
    {
        // Project.Expression instead of As<UserNotification>(): As<> reads all fields
        // of the document and matches strictly — Mongo has an autogenerated _id, the DTO does not,
        // which breaks the query. An explicit projection takes only the needed fields.
        return await Collection
            .Find(UserInterested(userId))
            .Sort(Sort.Descending(n => n.CreatedUtc))
            .Skip(pagingData.Skip)
            .Limit(pagingData.Take)
            .Project(n => new UserNotification
            {
                NotificationId = n.NotificationId,
                EventType = n.EventType,
                CreatedUtc = new DateTimeOffset(n.CreatedUtc, TimeSpan.Zero),
                Metadata = n.Metadata,
            })
            .ToListAsync();
    }

    // ═══ WRITE ═══

    /// <inheritdoc />
    public Task Create(IEnumerable<CreateNotificationEntity> notifications)
    {
        var entities = notifications.Select(n => new Notification
        {
            NotificationId = n.NotificationId,
            CreatedUtc = n.CreatedUtc.DateTime,
            UsersInterested = n.UsersInterested,
            UsersNotified = [],
            Metadata = n.Metadata,
            EventType = n.EventType
        });

        return Collection.InsertManyAsync(entities);
    }

    // AddToSet rather than Push: the UserToBeNotified filter is evaluated by the
    // server as part of the same update, so two requests racing each other both
    // pass it and Push would leave the same reader in the array twice.

    /// <inheritdoc />
    public Task MarkAsRead(Guid notificationId, Guid userId) =>
        Collection.UpdateOneAsync(
            Filter.Eq(n => n.NotificationId, notificationId) &
            UserToBeNotified(userId),
            Update.AddToSet(n => n.UsersNotified, userId));

    /// <inheritdoc />
    public Task MarkAsRead(Guid userId) =>
        Collection.UpdateManyAsync(
            UserToBeNotified(userId),
            Update.AddToSet(n => n.UsersNotified, userId));

    // ═══ PRIVATE ═══

    /// <summary>
    /// Filter out only notifications that given user is interested with
    /// </summary>
    private static FilterDefinition<Notification> UserInterested(Guid userId) =>
        Filter.AnyEq(n => n.UsersInterested, userId);

    /// <summary>
    /// Filter out only notifications that given user is interested with but haven't yet read
    /// </summary>
    private static FilterDefinition<Notification> UserToBeNotified(Guid userId) =>
        UserInterested(userId) &
        !Filter.AnyEq(n => n.UsersNotified, userId);
}
