<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DM.Domain.Game.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DM.Domain.Core\DM.Domain.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
