<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" VersionOverride="8.0.4" />
        <PackageReference Include="Testcontainers.MongoDb" VersionOverride="4.3.0" />
        <PackageReference Include="Testcontainers.PostgreSql" VersionOverride="4.3.0" />
        <PackageReference Include="Testcontainers.RabbitMq" VersionOverride="4.3.0" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DM.Tests.Core\DM.Tests.Core.csproj" />
        <ProjectReference Include="..\..\src\DM.Web.API\DM.Web.API.csproj" />
    </ItemGroup>

</Project>
