using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace DM.Infrastructure.Persistence.RelationalStorage;

/// <summary>
/// SSOT for the serial a readable page address is encoded from.
/// </summary>
/// <remarks>
/// Games, blogs and chats are addressed by Encode(SerialNumber), and the serial used to arrive
/// only with the insert: the row was written carrying a placeholder and a second SaveChanges
/// replaced it. The two writes commit separately and nothing wraps them, so anything that stops
/// the process between them leaves a row whose public address is a placeholder for good, and
/// every reader inside that window is handed the placeholder. Taking the number from the
/// sequence first turns the pair into one insert that already carries the final address.
///
/// A transaction around the two writes would close the same window, but not here: the execution
/// strategy the API host configures replays its block on a transient failure, and a replay that
/// clears the change tracker re-attaches an entity whose SerialNumber the failed attempt already
/// filled in. The column is GENERATED BY DEFAULT AS IDENTITY, so that value would be inserted
/// verbatim while the sequence still points at it — which is exactly the duplicate serial the
/// unique index on PublicId exists to refuse.
///
/// A rolled back insert burns its number and leaves a gap. That is the trade an identity column
/// already makes, and nothing reads the serial back: the encoded form is decoded nowhere.
///
/// Public rather than internal because the seeder writes the same three tables and used to carry
/// its own copy of the two-phase pair, placeholder and all — "SSOT" was true of the three
/// repositories and of nothing else.
/// </remarks>
public static class SerialNumberAllocator
{
    /// <summary>
    /// The next value of the SerialNumber identity sequence of
    /// <typeparamref name="TEntity" />'s table.
    /// </summary>
    public static async Task<int> NextAsync<TEntity>(
        DmDbContext dbContext,
        CancellationToken ct = default)
        where TEntity : class
    {
        // The table name comes from the model rather than from a literal, so a rename cannot
        // leave a string pointing at a table that no longer exists. Quoted because the
        // identifier is case-sensitive and pg_get_serial_sequence parses its first argument
        // the way SQL parses a name.
        var table = $"\"{dbContext.Model.FindEntityType(typeof(TEntity))!.GetTableName()}\"";

        var serialNumber = await dbContext.Database
            .SqlQuery<long>(
                $"SELECT nextval(pg_get_serial_sequence({table}, 'SerialNumber')) AS \"Value\"")
            .FirstAsync(ct);

        return (int) serialNumber;
    }
}
