<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DM.Domain.Personal.Tests" />
        <InternalsVisibleTo Include="DM.Domain.Personal.Tests.Notifications" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DM.Domain.Core\DM.Domain.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
    </ItemGroup>
</Project>
